version: "3"
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: pushbot
      POSTGRES_PASSWORD: shhh
    ports:
      - "5432"
  pushbot:
    build: .
    environment:
      PUSHBOT_DATABASE_URL: postgres://pushbot:shhh@postgres/pushbot
      HUBOT_MARKOV_STORAGE: postgres
      HUBOT_MARKOV_STORAGE_URL: postgres://pushbot:shhh@postgres/pushbot
      API_BASE_URL: http://localhost:8080
    depends_on:
      - postgres
